### ISSUE TITLE
Passing ReadStream by createReadStream to fluent-ffmpeg makes the program exit or hang

### ISSUE THREAD

**Issue by James4Ever0** [webtorrent/webtorrent#2464]
[Related issue](https://github.com/leeroybrun/webtorrent-transcode/issues/1) in [webtorrent-transcode](https://github.com/leeroybrun/webtorrent-transcode)

**What version of this package are you using?**

webtorrent 2.0.1

**What operating system, Node.js, and npm version?**

macOS Monterey 12.5
Node.js v18.11.0
npm 8.19.2

**What happened?**

Since `webtorrent` is an ESM module, I symlinked global node_modules to local directory by `ln -s $NODE_PATH node_modules`.

I execute this code:

```javascript
var torrentPath="/Users/jamesbrown/Downloads/somefile.torrent"

var selectedFilePath="somePath"

import ffmpeg from 'fluent-ffmpeg'
import WebTorrent from 'webtorrent'

console.log("WEBTORRENT OBJECT?",WebTorrent)
const client=new WebTorrent({dht: true}) 

client.add(torrentPath, torrent => {
    var selectedFile=torrent.files.find(file => {
        return file.path==selectedFilePath
    })

    var stream=selectedFile.createReadStream() 
// reading from local filesystem works.
    // var stream = fs.createReadStream("/Users/jamesbrown/Downloads/video.mp4")


     ffmpeg.ffprobe(stream,(err,data) => {
         if(err) {
             console.log("FFPROBE ERROR:",err)
         } else {
             console.log("FFPROBE METADATA:",data)
         }
     process.exit()
     })

})
```
On macOS it raises exceptions:

```
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16)
Emitted 'error' event on Readable instance at:
    at ReadableState.afterDestroy (/opt/homebrew/lib/node_modules/webtorrent/node_modules/streamx/index.js:449:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}

Node.js v18.11.0
```

If I comment out the line of `/opt/homebrew/lib/node_modules/webtorrent/node_modules/streamx/index.js:449:19` which is `if (err) stream.emit('error', err)`, I sometimes get another exception (it vanishes overnight, can't explain), but sometimes get metadata as expected.

The exception:

```
/opt/homebrew/lib/node_modules/fluent-ffmpeg/lib/ffprobe.js:169
            input.source.unpipe(ffprobe.stdin);
                         ^

TypeError: input.source.unpipe is not a function
    at Socket.<anonymous> (/opt/homebrew/lib/node_modules/fluent-ffmpeg/lib/ffprobe.js:169:26)
    at Socket.emit (node:events:525:35)
    at Pipe.<anonymous> (node:net:313:12)
```

On Termux (Android) the program hangs, not downloading, ffprobe hangs.

**What did you expect to happen?**

The program did not hang or exit, showing metadata of media stream.

**Workarounds**

By setting up server it allows seeking portions of file by ranges, and connecting it with ffmpeg/ffprobe via command line works, allowing seeking for given time ranges and getting media metadata before finished downloading, though occasionally fails because of corruption or truncated response.

**Are you willing to submit a pull request to fix this bug?**

I don't know the reason why this happens, but deeper understanding of `ReadStream` might help. Does `ReadStream` support seeking just like webtorrent file server?

Also is there anything else available to connect to `ffprobe` other than `createReadStream` or serving file via url?

Update: I found this issue is most related to [streamx](https://github.com/mafintosh/streamx/issues/71), at least on macOS. Thus I managed to patch the code like this:

```javascript
// stream is created using createReadStream
    stream.unpipe = (nodeStream) => {} //doing nothing?
    stream.on('error',function(err) {
        console.log('STREAM ERROR?',err);
        // just ignore it?
    })
```

On Termux (where the program just hangs) it needs more investigation. The installation process of `webtorrent` on Termux is different from macOS, which compiles some native code/library (maybe on macOS it is precompiled?), and might be the source of the blocking problem.

Update: The code above does not work. Though fetching metadataworks, trying to seek given time ranges with `fluent-ffmpeg` will stuck forever, like:

```javascript
 ffmpeg(stream).seekInput(60).duration(60).on('progress',function(progress) {
      console.log('FFmpeg Processing: '+progress.percent+'% done');
 }).on('end',() => {
        console.log("FFMPEG EXECUTION COMPLETE?")
        client.destroy()
        process.exit()
    }).outputOptions(['-c copy','-y']).output('output.mkv').run()
```

Which gives:

```
(node:37588) ExperimentalWarning: Importing JSON modules is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
WEBTORRENT OBJECT? [class WebTorrent extends EventEmitter] {
  WEBRTC_SUPPORT: false,
  UTP_SUPPORT: false,
  VERSION: '2.0.1'
}
FFmpeg Processing: undefined% done
FFmpeg Processing: undefined% done
STREAM ERROR? Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
STREAM ERROR? Error: Input stream error: write EPIPE
    at Readable.<anonymous> (/opt/homebrew/lib/node_modules/fluent-ffmpeg/lib/processor.js:452:34)
    at Readable.emit (node:events:525:35)
    at ReadableState.afterDestroy (/opt/homebrew/lib/node_modules/webtorrent/node_modules/streamx/index.js:449:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  inputStreamError: Error: write EPIPE
      at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16) {
    errno: -32,
    code: 'EPIPE',
    syscall: 'write'
  }
}
SPEED? 193380.8
SPEED? 480134.4
SPEED? 1098152.8
SPEED? 1338255.2
SPEED? 1748989.6
SPEED? 2785470.8
SPEED? 2902951.6
SPEED? 2690633.6
```

**Comment by ThaUnknown** [comment]
streamx streams arent exactly identical to node streams, but they are close, if you want 1:1 functionality, then webtorrent files are async iterable
```js
import { Readable } from 'stream'
const file = client.torrents[0].file

const stream = Readable.from(file)
```
but this won't work on web, unlike with streamx, only on node

also 2.0.1 has this small bug that if a file finishes downloading and then u create an iterator/stream it kinda yields the entire torrent instead of just the file, it's fixed, just not released yet

**Comment by ThaUnknown** [comment]
issues with streams yielding incorrect data have been fixed, and streamx doesn't support unpipe, as it's an anti-pattern, you can very easily create node streams with webtorrent files if you don't wish to use streamx, if you want more fine tune control over the data passed by the streams you can look at [the source code for their generation](https://github.com/webtorrent/webtorrent/blob/master/lib/file.js#L118-L128) which is really simple

any further issues would likely be caused by fluent-ffmpeg not webtorrent so I'm closing this

**Comment by James4Ever0** [comment]
I agree that `fluent-ffmpeg` might have issues, and I want to note that switching ReadStream implementations does not solve this issue completely.

First it will not show up progress (which gives `undefined`). When connecting to server, it has numeric progress indicators.

Second the file fetched from ReadStream with seeking will sometimes have visual lag or corrupt and even drop video stream completely, which does not happen when connecting to server.

I think it is because `ffmpeg` makes premises and handles media urls different from filesystem/pipe.

**Comment by ThaUnknown** [comment]
those aren't issues created by webtorrent, won't help you there
